## Python coding style and numpy basics

In [11]:
import numpy as np

In [12]:
# The Zen of Python
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

In [13]:
abc = np.arange(12).reshape(3,4)
abc

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
print(abc.sum())
print("  ")
print(abc.sum(axis=0))
print("  ")
print(abc.sum(axis=1))

66

[12 15 18 21]

[ 6 22 38]

In [15]:
?np.random.rand

## Use np.Vectorize to return functions

In [16]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n <0:
        return n.__class__(-1)
    else:
        return n

In [17]:
v = np.array([-1,3,5,-33,2])
noneg(-3)
noneg(v)

array([-1,  3,  5, -1,  2])

In [18]:
v1 = np.array([-1, 2, np.nan])

In [19]:
noneg(v1)

array([ -1.,   2.,  nan])

In [20]:
np.isnan(np.nan)

True

In [21]:
np.isnan(np.nan)

True

## Use Pandas Functions and usages
* Pandas read files
* pandas operations

The formula for logloss is $1/1+exp(-w.t*x)$

In [22]:
from os import path
fname = path.expanduser('~/Desktop_Abhik/Coursera_Advanced_ML_courses/Course_2_Kaggle_competiitions/kaggle_challenge_data/sales_train.csv')

In [23]:
!ls -lh "$fname"

-rw-r--r--@ 1 abhikbanerjee  staff    90M Feb 26 22:01 /Users/abhikbanerjee/Desktop_Abhik/Coursera_Advanced_ML_courses/Course_2_Kaggle_competiitions/kaggle_challenge_data/sales_train.csv

In [24]:
# get the path size of the filename
path.getsize(fname)/(1<<10)

92386.587890625

In [25]:
! head "$fname"

date,date_block_num,shop_id,item_id,item_price,item_cnt_day
02.01.2013,0,59,22154,999.0,1.0
03.01.2013,0,25,2552,899.0,1.0
05.01.2013,0,25,2552,899.0,-1.0
06.01.2013,0,25,2554,1709.05,1.0
15.01.2013,0,25,2555,1099.0,1.0
10.01.2013,0,25,2564,349.0,1.0
02.01.2013,0,25,2565,549.0,1.0
04.01.2013,0,25,2572,239.0,1.0
11.01.2013,0,25,2572,299.0,1.0

In [26]:
# get the first 10 lines of the file
with open(fname) as fp:
    for i,line in enumerate(fp):
        if i>10:
            break
        print(line[:-1]) # remove the new line at the end

date,date_block_num,shop_id,item_id,item_price,item_cnt_day
02.01.2013,0,59,22154,999.0,1.0
03.01.2013,0,25,2552,899.0,1.0
05.01.2013,0,25,2552,899.0,-1.0
06.01.2013,0,25,2554,1709.05,1.0
15.01.2013,0,25,2555,1099.0,1.0
10.01.2013,0,25,2564,349.0,1.0
02.01.2013,0,25,2565,549.0,1.0
04.01.2013,0,25,2572,239.0,1.0
11.01.2013,0,25,2572,299.0,1.0
03.01.2013,0,25,2573,299.0,3.0

In [27]:
!wc -l "$fname"

 2935850 /Users/abhikbanerjee/Desktop_Abhik/Coursera_Advanced_ML_courses/Course_2_Kaggle_competiitions/kaggle_challenge_data/sales_train.csv

In [28]:
with open(fname) as fp:
    print(sum(1 for line in fp))

2935850

In [29]:
import pandas as pd

df = pd.read_csv(fname, parse_dates=['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2935849 entries, 0 to 2935848
Data columns (total 6 columns):
date              datetime64[ns]
date_block_num    int64
shop_id           int64
item_id           int64
item_price        float64
item_cnt_day      float64
dtypes: datetime64[ns](1), float64(2), int64(3)
memory usage: 134.4 MB

In [30]:
df.head()

        date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0 2013-02-01               0       59    22154      999.00           1.0
1 2013-03-01               0       25     2552      899.00           1.0
2 2013-05-01               0       25     2552      899.00          -1.0
3 2013-06-01               0       25     2554     1709.05           1.0
4 2013-01-15               0       25     2555     1099.00           1.0

In [31]:
df.dtypes

date              datetime64[ns]
date_block_num             int64
shop_id                    int64
item_id                    int64
item_price               float64
item_cnt_day             float64
dtype: object

In [32]:
df.iloc[0:2]

        date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0 2013-02-01               0       59    22154       999.0           1.0
1 2013-03-01               0       25     2552       899.0           1.0

In [33]:
df.index

RangeIndex(start=0, stop=2935849, step=1)

### Use PyTz for timezone conversions

In [34]:
df.index = df['date']

In [35]:
df.index

DatetimeIndex(['2013-02-01', '2013-03-01', '2013-05-01', '2013-06-01',
               '2013-01-15', '2013-10-01', '2013-02-01', '2013-04-01',
               '2013-11-01', '2013-03-01',
               ...
               '2015-10-24', '2015-10-31', '2015-11-10', '2015-10-10',
               '2015-09-10', '2015-10-10', '2015-09-10', '2015-10-14',
               '2015-10-22', '2015-03-10'],
              dtype='datetime64[ns]', name='date', length=2935849, freq=None)

In [36]:
import pytz

In [37]:
df['date'].tz_localize(pytz.UTC).tz_convert(pytz.timezone('Asia/Jerusalem')).head()

date
2013-02-01 02:00:00+02:00   2013-02-01
2013-03-01 02:00:00+02:00   2013-03-01
2013-05-01 03:00:00+03:00   2013-05-01
2013-06-01 03:00:00+03:00   2013-06-01
2013-01-15 02:00:00+02:00   2013-01-15
Name: date, dtype: datetime64[ns]

In [38]:
import sys
sys.path

['',
 '/Users/abhikbanerjee/anaconda3/lib/python36.zip',
 '/Users/abhikbanerjee/anaconda3/lib/python3.6',
 '/Users/abhikbanerjee/anaconda3/lib/python3.6/lib-dynload',
 '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages',
 '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/aeosa',
 '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg',
 '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/Users/abhikbanerjee/.ipython']

In [39]:
!pwd

/Users/abhikbanerjee/Open_Source_Ml_Medium

In [1]:
import pandas as pd
sci_df = pd.read_csv("./science_federal_giving.csv")

/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,25,26,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
sci_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 881793 entries, 0 to 881792
Data columns (total 31 columns):
cmte_nm                 470203 non-null object
cmte_id                 470203 non-null object
cmte_tp                 470203 non-null object
cmte_pty                469997 non-null object
cand_name               383801 non-null object
cand_pty_affiliation    383796 non-null object
cand_office_st          383801 non-null object
cand_office             383801 non-null object
cand_office_district    383763 non-null float64
cand_status             383717 non-null object
rpt_tp                  470203 non-null object
transaction_pgi         430476 non-null object
transaction_tp          470203 non-null object
entity_tp               470157 non-null object
cleaned_name            470177 non-null object
city                    470125 non-null object
state                   469543 non-null object
zip_code                469642 non-null object
employer                467864 non-null object
cleanedoccupation       470203 non-null object
classification          470203 non-null object
transaction_dt          470196 non-null float64
cycle                   470196 non-null float64
transaction_amt         470203 non-null float64
2016_dollars            470174 non-null float64
other_id                98370 non-null object
tran_id                 470203 non-null object
file_num                470203 non-null float64
memo_cd                 3342 non-null object
memo_text               184170 non-null object
sub_id                  470203 non-null float64
dtypes: float64(7), object(24)
memory usage: 208.6+ MB

In [42]:
print(id(sci_df)) # gives the memory address
print(type(sci_df))  # gives the type

4937153280
<class 'pandas.core.frame.DataFrame'>

In [43]:
print(id(df)) # gives the memory address
print(type(df))  # gives the type

5995642720
<class 'pandas.core.frame.DataFrame'>

In [46]:
print(df.__doc__)
print(dir(df))

 Two-dimensional size-mutable, potentially heterogeneous tabular data
    structure with labeled axes (rows and columns). Arithmetic operations
    align on both row and column labels. Can be thought of as a dict-like
    container for Series objects. The primary pandas data structure

    Parameters
    ----------
    data : numpy ndarray (structured or homogeneous), dict, or DataFrame
        Dict can contain Series, arrays, constants, or list-like objects
    index : Index or array-like
        Index to use for resulting frame. Will default to np.arange(n) if
        no indexing information part of input data and no index provided
    columns : Index or array-like
        Column labels to use for resulting frame. Will default to
        np.arange(n) if no column labels are provided
    dtype : dtype, default None
        Data type to force, otherwise infer
    copy : boolean, default False
        Copy data from inputs. Only affects DataFrame / 2d ndarray input

    Examples
    --------
    >>> d = {'col1': ts1, 'col2': ts2}
    >>> df = DataFrame(data=d, index=index)
    >>> df2 = DataFrame(np.random.randn(10, 5))
    >>> df3 = DataFrame(np.random.randn(10, 5),
    ...                 columns=['a', 'b', 'c', 'd', 'e'])

    See also
    --------
    DataFrame.from_records : constructor from tuples, also record arrays
    DataFrame.from_dict : from dicts of Series, arrays, or dicts
    DataFrame.from_items : from sequence of (key, value) pairs
    pandas.read_csv, pandas.read_table, pandas.read_clipboard

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__le__', '__len__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__unicode__', '__weakref__', '__xor__', '_accessors', '_add_numeric_operations', '_add_series_only_operations', '_add_series_or_dataframe_operations', '_agg_by_level', '_agg_doc', '_aggregate', '_aggregate_multiple_funcs', '_align_frame', '_align_series', '_apply_broadcast', '_apply_empty_result', '_apply_raw', '_apply_standard', '_at', '_box_col_values', '_box_item_values', '_builtin_table', '_check_inplace_setting', '_check_is_chained_assignment_possible', '_check_percentile', '_check_setitem_copy', '_clear_item_cache', '_clip_with_scalar', '_combine_const', '_combine_frame', '_combine_match_columns', '_combine_match_index', '_combine_series', '_combine_series_infer', '_compare_frame', '_compare_frame_evaluate', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_axes_dict_for_slice', '_construct_axes_dict_from', '_construct_axes_from_arguments', '_constructor', '_constructor_expanddim', '_constructor_sliced', '_convert', '_count_level', '_create_indexer', '_cython_table', '_dir_additions', '_dir_deletions', '_ensure_valid_index', '_expand_axes', '_flex_compare_frame', '_from_arrays', '_from_axes', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_index_resolvers', '_get_item_cache', '_get_numeric_data', '_get_values', '_getitem_array', '_getitem_column', '_getitem_frame', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_iat', '_iget_item_cache', '_iloc', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_dict', '_init_mgr', '_init_ndarray', '_internal_names', '_internal_names_set', '_is_builtin_func', '_is_cached', '_is_cython_func', '_is_datelike_mixed_type', '_is_mixed_type', '_is_numeric_mixed_type', '_is_view', '_ix', '_ixs', '_join_compat', '_loc', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_needs_reindex_multi', '_obj_with_exclusions', '_protect_consolidate', '_reduce', '_reindex_axes', '_reindex_axis', '_reindex_columns', '_reindex_index', '_reindex_multi', '_reindex_with_indexers', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_selected_obj', '_selection', '_selection_list', '_selection_name', '_series', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_is_copy', '_set_item', '_setitem_array', '_setitem_frame', '_setitem_slice', '_setup_axes', '_shallow_copy', '_slice', '_stat_axis', '_stat_axis_name', '_stat_axis_number', '_try_aggregate_string_function', '_typ', '_unpickle_frame_compat', '_unpickle_matrix_compat', '_update_inplace', '_validate_dtype', '_values', '_where', '_xs', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'append', 'apply', 'applymap', 'as_blocks', 'as_matrix', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'axes', 'between_time', 'bfill', 'blocks', 'bool', 'boxplot', 'clip', 'clip_lower', 'clip_upper', 'columns', 'combine', 'combine_first', 'compound', 'consolidate', 'convert_objects', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'date', 'date_block_num', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'floordiv', 'from_csv', 'from_dict', 'from_items', 'from_records', 'ftypes', 'ge', 'get', 'get_dtype_counts', 'get_ftype_counts', 'get_value', 'get_values', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'info', 'insert', 'interpolate', 'is_copy', 'isin', 'isnull', 'item_cnt_day', 'item_id', 'item_price', 'items', 'iteritems', 'iterrows', 'itertuples', 'ix', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lookup', 'lt', 'mad', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_axis', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select', 'select_dtypes', 'sem', 'set_axis', 'set_index', 'set_value', 'shape', 'shift', 'shop_id', 'size', 'skew', 'slice_shift', 'sort_index', 'sort_values', 'sortlevel', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dense', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_msgpack', 'to_panel', 'to_period', 'to_pickle', 'to_records', 'to_sparse', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tshift', 'tz_convert', 'tz_localize', 'unstack', 'update', 'values', 'var', 'where', 'xs']

In [47]:
globals()

{'In': ['',
  'import pandas as pd\nsci_df = pd.read_csv("./science_federal_giving.csv")',
  'sci_df.head()',
  'sci_df.transpose().head()',
  'sci_df.head()',
  'sci_df.columns',
  'sci_df.info()',
  'sci_df.summary()',
  'sci_df.summary',
  'sci_df.dtypes',
  "df['date'].tz_localize(pytz.UTC).tz_convert(pytz.timezone('Asia/Jerusalem')).head()",
  'import numpy as np',
  '# The Zen of Python\nimport this',
  'abc = np.arange(12).reshape(3,4)\nabc',
  'print(abc.sum())\nprint("  ")\nprint(abc.sum(axis=0))\nprint("  ")\nprint(abc.sum(axis=1))',
  "get_ipython().magic('pinfo np.random.rand')",
  '@np.vectorize\ndef noneg(n):\n    if not np.isnan(n) and n <0:\n        return n.__class__(-1)\n    else:\n        return n',
  'v = np.array([-1,3,5,-33,2])\nnoneg(-3)\nnoneg(v)',
  'v1 = np.array([-1, 2, np.nan])',
  'noneg(v1)',
  'np.isnan(np.nan)',
  'np.isnan(np.nan)',
  "from os import path\nfname = path.expanduser('~/Desktop_Abhik/Coursera_Advanced_ML_courses/Course_2_Kaggle_competiitions/kaggle_challenge_data/sales_train.csv')",
  'get_ipython().system(\'ls -lh "$fname"\')',
  '# get the path size of the filename\npath.getsize(fname)/(1<<10)',
  'get_ipython().system(\' head "$fname"\')',
  '# get the first 10 lines of the file\nwith open(fname) as fp:\n    for i,line in enumerate(fp):\n        if i>10:\n            break\n        print(line[:-1]) # remove the new line at the end',
  'get_ipython().system(\'wc -l "$fname"\')',
  'with open(fname) as fp:\n    print(sum(1 for line in fp))',
  "import pandas as pd\n\ndf = pd.read_csv(fname, parse_dates=['date'])\ndf.info()",
  'df.head()',
  'df.dtypes',
  'df.iloc[0:2]',
  'df.index',
  "df.index = df['date']",
  'df.index',
  'import pytz',
  "df['date'].tz_localize(pytz.UTC).tz_convert(pytz.timezone('Asia/Jerusalem')).head()",
  'import sys\nsys.path',
  "get_ipython().system('pwd')",
  'id(sci_df)',
  'id(df)',
  'print(id(sci_df)) # gives the memory address\nprint(type(sci_df))  # gives the type',
  'print(id(df)) # gives the memory address\nprint(type(df))  # gives the type',
  'dir(df)',
  'df.__doc__',
  'print(df.__doc__)\nprint(dir(df))',
  'globals()'],
 'Out': {2:                                              cmte_nm    cmte_id cmte_tp  \
  0                    AMERICAN WAY - DURANT 2012; THE  C00501452       S
  1                      A LOT OF PEOPLE FOR DAVE OBEY  C00017830       H
  2  A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...  C00374058       H
  3  A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...  C00374058       H
  4  A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...  C00374058       H

    cmte_pty         cand_name cand_pty_affiliation cand_office_st cand_office  \
  0      REP     DURANT, CLARK                  REP             MI           S
  1      DEM     OBEY, DAVID R                  DEM             WI           H
  2      DEM  GRIJALVA, RAUL M                  DEM             AZ           H
  3      DEM  GRIJALVA, RAUL M                  DEM             AZ           H
  4      DEM  GRIJALVA, RAUL M                  DEM             AZ           H

     cand_office_district cand_status      ...      transaction_dt   cycle  \
  0                   0.0           C      ...           3302012.0  2012.0
  1                   7.0           C      ...           4182007.0  2008.0
  2                   3.0           C      ...           6092016.0  2016.0
  3                   3.0           C      ...           8192012.0  2012.0
  4                   7.0           C      ...          10292010.0  2010.0

    transaction_amt 2016_dollars   other_id          tran_id   file_num memo_cd  \
  0          2500.0      2612.50        NaN  SA0108160812336   845273.0     NaN
  1           250.0       292.50        NaN           C34559   294636.0     NaN
  2            50.0        50.00  C00401224      VSH8VCDY4S4  1096417.0     NaN
  3          2500.0      2612.50        NaN         C6548162   863428.0     NaN
  4           250.0       273.25        NaN         C5156783   863417.0     NaN

                               memo_text        sub_id
  0                                  NaN  1.010000e+18
  1                                  NaN  4.070000e+18
  2  * EARMARKED CONTRIBUTION: SEE BELOW  4.080000e+18
  3                                  NaN  4.030000e+18
  4                                  NaN  4.030000e+18

  [5 rows x 31 columns],
  3:                                     0                              1       \
  cmte_nm    AMERICAN WAY - DURANT 2012; THE  A LOT OF PEOPLE FOR DAVE OBEY
  cmte_id                          C00501452                      C00017830
  cmte_tp                                  S                              H
  cmte_pty                               REP                            DEM
  cand_name                    DURANT, CLARK                  OBEY, DAVID R

                                                        2       \
  cmte_nm    A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...
  cmte_id                                            C00374058
  cmte_tp                                                    H
  cmte_pty                                                 DEM
  cand_name                                   GRIJALVA, RAUL M

                                                        3       \
  cmte_nm    A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...
  cmte_id                                            C00374058
  cmte_tp                                                    H
  cmte_pty                                                 DEM
  cand_name                                   GRIJALVA, RAUL M

                                                        4       \
  cmte_nm    A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...
  cmte_id                                            C00374058
  cmte_tp                                                    H
  cmte_pty                                                 DEM
  cand_name                                   GRIJALVA, RAUL M

                                                        5       \
  cmte_nm    A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...
  cmte_id                                            C00374058
  cmte_tp                                                    H
  cmte_pty                                                 DEM
  cand_name                                   GRIJALVA, RAUL M

                                                        6       \
  cmte_nm    A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...
  cmte_id                                            C00374058
  cmte_tp                                                    H
  cmte_pty                                                 DEM
  cand_name                                   GRIJALVA, RAUL M

                                                        7       \
  cmte_nm    A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...
  cmte_id                                            C00374058
  cmte_tp                                                    H
  cmte_pty                                                 DEM
  cand_name                                   GRIJALVA, RAUL M

                                  8                         9       \
  cmte_nm    ABEL MALDONADO FOR CONGRESS  ABERCROMBIE FOR CONGRESS
  cmte_id                      C00493379                 C00247379
  cmte_tp                              H                         H
  cmte_pty                           REP                       DEM
  cand_name              MALDONADO, ABEL         ABERCROMBIE, NEIL

                    ...                                881783  \
  cmte_nm           ...          ZEPHYR TEACHOUT FOR CONGRESS
  cmte_id           ...                             C00608174
  cmte_tp           ...                                     H
  cmte_pty          ...                                   DEM
  cand_name         ...                      TEACHOUT, ZEPHYR

                                   881784                        881785  \
  cmte_nm    ZEPHYR TEACHOUT FOR CONGRESS  ZEPHYR TEACHOUT FOR CONGRESS
  cmte_id                       C00608174                     C00608174
  cmte_tp                               H                             H
  cmte_pty                            DEM                           DEM
  cand_name              TEACHOUT, ZEPHYR              TEACHOUT, ZEPHYR

                            881786                 881787              881788  \
  cmte_nm    ZIMMER FOR SENATE INC  ZIMMER FOR SENATE INC  ZINKE FOR CONGRESS
  cmte_id                C00449074              C00449074           C00550871
  cmte_tp                        S                      S                   H
  cmte_pty                     REP                    REP                 REP
  cand_name           ZIMMER, DICK           ZIMMER, DICK       ZINKE, RYAN K

                         881789              881790              881791  \
  cmte_nm    ZINKE FOR CONGRESS  ZINKE FOR CONGRESS  ZINKE FOR CONGRESS
  cmte_id             C00550871           C00550871           C00550871
  cmte_tp                     H                   H                   H
  cmte_pty                  REP                 REP                 REP
  cand_name       ZINKE, RYAN K       ZINKE, RYAN K       ZINKE, RYAN K

                         881792
  cmte_nm    ZINKE FOR CONGRESS
  cmte_id             C00550871
  cmte_tp                     H
  cmte_pty                  REP
  cand_name       ZINKE, RYAN K

  [5 rows x 881793 columns],
  4:                                              cmte_nm    cmte_id cmte_tp  \
  0                    AMERICAN WAY - DURANT 2012; THE  C00501452       S
  1                      A LOT OF PEOPLE FOR DAVE OBEY  C00017830       H
  2  A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...  C00374058       H
  3  A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...  C00374058       H
  4  A WHOLE LOT OF PEOPLE FOR GRIJALVA CONGRESSION...  C00374058       H

    cmte_pty         cand_name cand_pty_affiliation cand_office_st cand_office  \
  0      REP     DURANT, CLARK                  REP             MI           S
  1      DEM     OBEY, DAVID R                  DEM             WI           H
  2      DEM  GRIJALVA, RAUL M                  DEM             AZ           H
  3      DEM  GRIJALVA, RAUL M                  DEM             AZ           H
  4      DEM  GRIJALVA, RAUL M                  DEM             AZ           H

     cand_office_district cand_status      ...      transaction_dt   cycle  \
  0                   0.0           C      ...           3302012.0  2012.0
  1                   7.0           C      ...           4182007.0  2008.0
  2                   3.0           C      ...           6092016.0  2016.0
  3                   3.0           C      ...           8192012.0  2012.0
  4                   7.0           C      ...          10292010.0  2010.0

    transaction_amt 2016_dollars   other_id          tran_id   file_num memo_cd  \
  0          2500.0      2612.50        NaN  SA0108160812336   845273.0     NaN
  1           250.0       292.50        NaN           C34559   294636.0     NaN
  2            50.0        50.00  C00401224      VSH8VCDY4S4  1096417.0     NaN
  3          2500.0      2612.50        NaN         C6548162   863428.0     NaN
  4           250.0       273.25        NaN         C5156783   863417.0     NaN

                               memo_text        sub_id
  0                                  NaN  1.010000e+18
  1                                  NaN  4.070000e+18
  2  * EARMARKED CONTRIBUTION: SEE BELOW  4.080000e+18
  3                                  NaN  4.030000e+18
  4                                  NaN  4.030000e+18

  [5 rows x 31 columns],
  5: Index(['cmte_nm', 'cmte_id', 'cmte_tp', 'cmte_pty', 'cand_name',
         'cand_pty_affiliation', 'cand_office_st', 'cand_office',
         'cand_office_district', 'cand_status', 'rpt_tp', 'transaction_pgi',
         'transaction_tp', 'entity_tp', 'cleaned_name', 'city', 'state',
         'zip_code', 'employer', 'cleanedoccupation', 'classification',
         'transaction_dt', 'cycle', 'transaction_amt', '2016_dollars',
         'other_id', 'tran_id', 'file_num', 'memo_cd', 'memo_text', 'sub_id'],
        dtype='object'),
  9: cmte_nm                  object
  cmte_id                  object
  cmte_tp                  object
  cmte_pty                 object
  cand_name                object
  cand_pty_affiliation     object
  cand_office_st           object
  cand_office              object
  cand_office_district    float64
  cand_status              object
  rpt_tp                   object
  transaction_pgi          object
  transaction_tp           object
  entity_tp                object
  cleaned_name             object
  city                     object
  state                    object
  zip_code                 object
  employer                 object
  cleanedoccupation        object
  classification           object
  transaction_dt          float64
  cycle                   float64
  transaction_amt         float64
  2016_dollars            float64
  other_id                 object
  tran_id                  object
  file_num                float64
  memo_cd                  object
  memo_text                object
  sub_id                  float64
  dtype: object,
  13: array([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
  17: array([-1,  3,  5, -1,  2]),
  19: array([ -1.,   2.,  nan]),
  20: True,
  21: True,
  24: 92386.587890625,
  30:         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
  0 2013-02-01               0       59    22154      999.00           1.0
  1 2013-03-01               0       25     2552      899.00           1.0
  2 2013-05-01               0       25     2552      899.00          -1.0
  3 2013-06-01               0       25     2554     1709.05           1.0
  4 2013-01-15               0       25     2555     1099.00           1.0,
  31: date              datetime64[ns]
  date_block_num             int64
  shop_id                    int64
  item_id                    int64
  item_price               float64
  item_cnt_day             float64
  dtype: object,
  32:         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
  0 2013-02-01               0       59    22154       999.0           1.0
  1 2013-03-01               0       25     2552       899.0           1.0,
  33: RangeIndex(start=0, stop=2935849, step=1),
  35: DatetimeIndex(['2013-02-01', '2013-03-01', '2013-05-01', '2013-06-01',
                 '2013-01-15', '2013-10-01', '2013-02-01', '2013-04-01',
                 '2013-11-01', '2013-03-01',
                 ...
                 '2015-10-24', '2015-10-31', '2015-11-10', '2015-10-10',
                 '2015-09-10', '2015-10-10', '2015-09-10', '2015-10-14',
                 '2015-10-22', '2015-03-10'],
                dtype='datetime64[ns]', name='date', length=2935849, freq=None),
  37: date
  2013-02-01 02:00:00+02:00   2013-02-01
  2013-03-01 02:00:00+02:00   2013-03-01
  2013-05-01 03:00:00+03:00   2013-05-01
  2013-06-01 03:00:00+03:00   2013-06-01
  2013-01-15 02:00:00+02:00   2013-01-15
  Name: date, dtype: datetime64[ns],
  38: ['',
   '/Users/abhikbanerjee/anaconda3/lib/python36.zip',
   '/Users/abhikbanerjee/anaconda3/lib/python3.6',
   '/Users/abhikbanerjee/anaconda3/lib/python3.6/lib-dynload',
   '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages',
   '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/aeosa',
   '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg',
   '/Users/abhikbanerjee/anaconda3/lib/python3.6/site-packages/IPython/extensions',
   '/Users/abhikbanerjee/.ipython'],
  40: 4937153280,
  41: 5995642720,
  44: ['T',
   '_AXIS_ALIASES',
   '_AXIS_IALIASES',
   '_AXIS_LEN',
   '_AXIS_NAMES',
   '_AXIS_NUMBERS',
   '_AXIS_ORDERS',
   '_AXIS_REVERSED',
   '_AXIS_SLICEMAP',
   '__abs__',
   '__add__',
   '__and__',
   '__array__',
   '__array_wrap__',
   '__bool__',
   '__bytes__',
   '__class__',
   '__contains__',
   '__copy__',
   '__deepcopy__',
   '__delattr__',
   '__delitem__',
   '__dict__',
   '__dir__',
   '__div__',
   '__doc__',
   '__eq__',
   '__finalize__',
   '__floordiv__',
   '__format__',
   '__ge__',
   '__getattr__',
   '__getattribute__',
   '__getitem__',
   '__getstate__',
   '__gt__',
   '__hash__',
   '__iadd__',
   '__imul__',
   '__init__',
   '__init_subclass__',
   '__invert__',
   '__ipow__',
   '__isub__',
   '__iter__',
   '__itruediv__',
   '__le__',
   '__len__',
   '__lt__',
   '__mod__',
   '__module__',
   '__mul__',
   '__ne__',
   '__neg__',
   '__new__',
   '__nonzero__',
   '__or__',
   '__pow__',
   '__radd__',
   '__rand__',
   '__rdiv__',
   '__reduce__',
   '__reduce_ex__',
   '__repr__',
   '__rfloordiv__',
   '__rmod__',
   '__rmul__',
   '__ror__',
   '__round__',
   '__rpow__',
   '__rsub__',
   '__rtruediv__',
   '__rxor__',
   '__setattr__',
   '__setitem__',
   '__setstate__',
   '__sizeof__',
   '__str__',
   '__sub__',
   '__subclasshook__',
   '__truediv__',
   '__unicode__',
   '__weakref__',
   '__xor__',
   '_accessors',
   '_add_numeric_operations',
   '_add_series_only_operations',
   '_add_series_or_dataframe_operations',
   '_agg_by_level',
   '_agg_doc',
   '_aggregate',
   '_aggregate_multiple_funcs',
   '_align_frame',
   '_align_series',
   '_apply_broadcast',
   '_apply_empty_result',
   '_apply_raw',
   '_apply_standard',
   '_at',
   '_box_col_values',
   '_box_item_values',
   '_builtin_table',
   '_check_inplace_setting',
   '_check_is_chained_assignment_possible',
   '_check_percentile',
   '_check_setitem_copy',
   '_clear_item_cache',
   '_clip_with_scalar',
   '_combine_const',
   '_combine_frame',
   '_combine_match_columns',
   '_combine_match_index',
   '_combine_series',
   '_combine_series_infer',
   '_compare_frame',
   '_compare_frame_evaluate',
   '_consolidate',
   '_consolidate_inplace',
   '_construct_axes_dict',
   '_construct_axes_dict_for_slice',
   '_construct_axes_dict_from',
   '_construct_axes_from_arguments',
   '_constructor',
   '_constructor_expanddim',
   '_constructor_sliced',
   '_convert',
   '_count_level',
   '_create_indexer',
   '_cython_table',
   '_dir_additions',
   '_dir_deletions',
   '_ensure_valid_index',
   '_expand_axes',
   '_flex_compare_frame',
   '_from_arrays',
   '_from_axes',
   '_get_agg_axis',
   '_get_axis',
   '_get_axis_name',
   '_get_axis_number',
   '_get_axis_resolvers',
   '_get_block_manager_axis',
   '_get_bool_data',
   '_get_cacher',
   '_get_index_resolvers',
   '_get_item_cache',
   '_get_numeric_data',
   '_get_values',
   '_getitem_array',
   '_getitem_column',
   '_getitem_frame',
   '_getitem_multilevel',
   '_getitem_slice',
   '_gotitem',
   '_iat',
   '_iget_item_cache',
   '_iloc',
   '_indexed_same',
   '_info_axis',
   '_info_axis_name',
   '_info_axis_number',
   '_info_repr',
   '_init_dict',
   '_init_mgr',
   '_init_ndarray',
   '_internal_names',
   '_internal_names_set',
   '_is_builtin_func',
   '_is_cached',
   '_is_cython_func',
   '_is_datelike_mixed_type',
   '_is_mixed_type',
   '_is_numeric_mixed_type',
   '_is_view',
   '_ix',
   '_ixs',
   '_join_compat',
   '_loc',
   '_maybe_cache_changed',
   '_maybe_update_cacher',
   '_metadata',
   '_needs_reindex_multi',
   '_obj_with_exclusions',
   '_protect_consolidate',
   '_reduce',
   '_reindex_axes',
   '_reindex_axis',
   '_reindex_columns',
   '_reindex_index',
   '_reindex_multi',
   '_reindex_with_indexers',
   '_repr_data_resource_',
   '_repr_fits_horizontal_',
   '_repr_fits_vertical_',
   '_repr_html_',
   '_repr_latex_',
   '_reset_cache',
   '_reset_cacher',
   '_sanitize_column',
   '_selected_obj',
   '_selection',
   '_selection_list',
   '_selection_name',
   '_series',
   '_set_as_cached',
   '_set_axis',
   '_set_axis_name',
   '_set_is_copy',
   '_set_item',
   '_setitem_array',
   '_setitem_frame',

In [56]:
with open("./science_federal_giving.csv","r") as file:
    file_data = file.read()
    print(file_data.count('.'))

950294

In [4]:
import pandas as pd
df = pd.read_csv("/Users/abhikbanerjee/auto-ml/joined_data_flatenner_20180321")
df.head(n=50)

,[riid],hash_email,email_permission,email_deliver,email_domain,email_isp,mob_permission,mob_deliverability,city,state,postal_code,country,created_date,modified_date,acc_id,description,event_dt,launch_status,launch_type,new_event_type
0,65133942,f394cd28c5be8c22bd592741c8c6209abb43d242924e8...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:26:07,2018-03-14 14:26:07,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
1,65133942,f394cd28c5be8c22bd592741c8c6209abb43d242924e8...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:26:07,2018-03-14 14:26:07,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
2,65133942,f394cd28c5be8c22bd592741c8c6209abb43d242924e8...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:26:07,2018-03-14 14:26:07,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
3,62495502,fb670cc67c6aa762032f50fcba7d92606888299401eef...,I,D,gmail.com,Gmail,O,D,,,,,2018-02-14 14:38:01,2018-03-14 14:19:14,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
4,62495502,fb670cc67c6aa762032f50fcba7d92606888299401eef...,I,D,gmail.com,Gmail,O,D,,,,,2018-02-14 14:38:01,2018-03-14 14:19:14,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
5,62495502,fb670cc67c6aa762032f50fcba7d92606888299401eef...,I,D,gmail.com,Gmail,O,D,,,,,2018-02-14 14:38:01,2018-03-14 14:19:14,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
6,57869862,1aba7f388de0b2e2b55a8dcdcba5897ff26395a93dd01...,I,D,gmail.com,Gmail,I,D,,,,,2018-01-17 18:35:56,2018-03-14 14:56:15,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
7,57869862,1aba7f388de0b2e2b55a8dcdcba5897ff26395a93dd01...,I,D,gmail.com,Gmail,I,D,,,,,2018-01-17 18:35:56,2018-03-14 14:56:15,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
8,57869862,1aba7f388de0b2e2b55a8dcdcba5897ff26395a93dd01...,I,D,gmail.com,Gmail,I,D,,,,,2018-01-17 18:35:56,2018-03-14 14:56:15,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
9,30875862,4bfc2f52a5845d241d3688c8415e1c6645bb1a23bd2a5...,I,D,gmail.com,Gmail,I,D,,,,,2017-04-17 03:35:00,2018-03-14 12:48:57,9653.0,,N/A,B,S,0.0
10,30875862,4bfc2f52a5845d241d3688c8415e1c6645bb1a23bd2a5...,I,D,gmail.com,Gmail,I,D,,,,,2017-04-17 03:35:00,2018-03-14 12:48:57,9653.0,,N/A,L,S,0.0
11,30875862,4bfc2f52a5845d241d3688c8415e1c6645bb1a23bd2a5...,I,D,gmail.com,Gmail,I,D,,,,,2017-04-17 03:35:00,2018-03-14 12:48:57,9653.0,,N/A,C,S,0.0
12,65125802,a0e2709ff21903c3adbe39169dd9036a1c596485c65d4...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 12:39:24,2018-03-14 12:39:24,9653.0,,N/A,B,S,0.0
13,65125802,a0e2709ff21903c3adbe39169dd9036a1c596485c65d4...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 12:39:24,2018-03-14 12:39:24,9653.0,,N/A,L,S,0.0
14,65125802,a0e2709ff21903c3adbe39169dd9036a1c596485c65d4...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 12:39:24,2018-03-14 12:39:24,9653.0,,N/A,C,S,0.0
15,65128782,7852506dfcafe362a7aaa6630373009b667792e2e2a45...,I,D,outlook.com,Hotmail,I,D,,,,,2018-03-14 13:19:11,2018-03-14 13:19:11,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
16,65128782,7852506dfcafe362a7aaa6630373009b667792e2e2a45...,I,D,outlook.com,Hotmail,I,D,,,,,2018-03-14 13:19:11,2018-03-14 13:19:11,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
17,65128782,7852506dfcafe362a7aaa6630373009b667792e2e2a45...,I,D,outlook.com,Hotmail,I,D,,,,,2018-03-14 13:19:11,2018-03-14 13:19:11,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
18,65134802,2db806def4406c961fe0f79cc91b18a2be8da2bd252e1...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:38:52,2018-03-14 14:38:52,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
19,65134802,2db806def4406c961fe0f79cc91b18a2be8da2bd252e1...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:38:52,2018-03-14 14:38:52,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
20,65134802,2db806def4406c961fe0f79cc91b18a2be8da2bd252e1...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:38:52,2018-03-14 14:38:52,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
21,65132682,753a5f53e7eb0665179357e3eb1f7526bdebae65d4412...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:09:17,2018-03-14 14:09:17,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
22,65132682,753a5f53e7eb0665179357e3eb1f7526bdebae65d4412...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:09:17,2018-03-14 14:09:17,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
23,65132682,753a5f53e7eb0665179357e3eb1f7526bdebae65d4412...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:09:17,2018-03-14 14:09:17,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
24,24675562,e8f4195f4b19feda12f7a873d43592ab2d4de3eab2a09...,I,D,gmail.com,Gmail,I,D,,,,,2017-03-07 04:45:32,2018-03-14 13:26:36,9653.0,,14-Mar-2018 22:15:56,B,S,1.0
25,24675562,e8f4195f4b19feda12f7a873d43592ab2d4de3eab2a09...,I,D,gmail.com,Gmail,I,D,,,,,2017-03-07 04:45:32,2018-03-14 13:26:36,9653.0,,14-Mar-2018 22:15:56,C,S,1.0
26,24675562,e8f4195f4b19feda12f7a873d43592ab2d4de3eab2a09...,I,D,gmail.com,Gmail,I,D,,,,,2017-03-07 04:45:32,2018-03-14 13:26:36,9653.0,,14-Mar-2018 22:15:56,L,S,1.0
27,65127962,7ac10b1460e8cbf3c2fd6748720ec76a9336c3b6d2720...,I,D,hotmail.com,Hotmail,I,D,,,,,2018-03-14 13:09:50,2018-03-14 13:09:50,9653.0,,N/A,B,S,0.0
28,65127962,7ac10b1460e8cbf3c2fd6748720ec76a9336c3b6d2720...,I,D,hotmail.com,Hotmail,I,D,,,,,2018-03-14 13:09:50,2018-03-14 13:09:50,9653.0,,N/A,C,S,0.0
29,65127962,7ac10b1460e8cbf3c2fd6748720ec76a9336c3b6d2720...,I,D,hotmail.com,Hotmail,I,D,,,,,2018-03-14 13:09:50,2018-03-14 13:09:50,9653.0,,N/A,L,S,0.0
30,48726162,6dbd20c13c96f9300839114af269606de590284c82127...,I,D,hotmail.com,Hotmail,I,D,,,,,2017-10-08 13:46:08,2018-03-14 13:26:36,9653.0,,N/A,B,S,0.0
31,48726162,6dbd20c13c96f9300839114af269606de590284c82127...,I,D,hotmail.com,Hotmail,I,D,,,,,2017-10-08 13:46:08,2018-03-14 13:26:36,9653.0,,N/A,C,S,0.0
32,48726162,6dbd20c13c96f9300839114af269606de590284c82127...,I,D,hotmail.com,Hotmail,I,D,,,,,2017-10-08 13:46:08,2018-03-14 13:26:36,9653.0,,N/A,L,S,0.0
33,24500862,29874bc4fa76ce2020e06e80354672a9518d7297b74eb...,I,D,hotmail.com,Hotmail,O,D,,,,,2017-03-05 06:35:06,2018-03-14 14:56:15,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
34,24500862,29874bc4fa76ce2020e06e80354672a9518d7297b74eb...,I,D,hotmail.com,Hotmail,O,D,,,,,2017-03-05 06:35:06,2018-03-14 14:56:15,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
35,24500862,29874bc4fa76ce2020e06e80354672a9518d7297b74eb...,I,D,hotmail.com,Hotmail,O,D,,,,,2017-03-05 06:35:06,2018-03-14 14:56:15,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
36,65135942,bd66343a6530744575c694e2b1181ae8e5fe3659d614b...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:56:15,2018-03-14 14:56:15,9653.0,,N/A,B,S,0.0
37,65135942,bd66343a6530744575c694e2b1181ae8e5fe3659d614b...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:56:15,2018-03-14 14:56:15,9653.0,,N/A,C,S,0.0
38,65135942,bd66343a6530744575c694e2b1181ae8e5fe3659d614b...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-14 14:56:15,2018-03-14 14:56:15,9653.0,,N/A,L,S,0.0
39,59995542,596f23e49cf438371da9735bfecaf048391114093007c...,I,D,outlook.com,Hotmail,I,D,,,,,2018-02-09 08:10:51,2018-03-14 12:10:43,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
40,59995542,596f23e49cf438371da9735bfecaf048391114093007c...,I,D,outlook.com,Hotmail,I,D,,,,,2018-02-09 08:10:51,2018-03-14 12:10:43,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
41,59995542,596f23e49cf438371da9735bfecaf048391114093007c...,I,D,outlook.com,Hotmail,I,D,,,,,2018-02-09 08:10:51,2018-03-14 12:10:43,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
42,63908762,40533e68fb6d39252d65870d99136a94829e861ed98f9...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-02 02:26:58,2018-03-14 12:48:57,9653.0,,N/A,B,S,0.0
43,63908762,40533e68fb6d39252d65870d99136a94829e861ed98f9...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-02 02:26:58,2018-03-14 12:48:57,9653.0,,N/A,L,S,0.0
44,63908762,40533e68fb6d39252d65870d99136a94829e861ed98f9...,I,D,gmail.com,Gmail,I,D,,,,,2018-03-02 02:26:58,2018-03-14 12:48:57,9653.0,,N/A,C,S,0.0
45,65132662,377ed3cd98a422642cc340bb3084b950b8666d7388eae...,I,D,88hotmail.com,Other,I,D,,,,,2018-03-14 14:09:17,2018-03-14 14:09:17,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
46,65132662,377ed3cd98a422642cc340bb3084b950b8666d7388eae...,I,D,88hotmail.com,Other,I,D,,,,,2018-03-14 14:09:17,2018-03-14 14:09:17,9653.0,AUS - Join Day to Accept,N/A,B,S,0.0
47,65132662,377ed3cd98a422642cc340bb3084b950b8666d7388eae...,I,D,88hotmail.com,Other,I,D,,,,,2018-03-14 14:09:17,2018-03-14 14:09:17,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0
48,24144882,ded5f6086e735459e8aaf0cecddd8798ff8fe920e9432...,I,D,live.com.au,Hotmail,O,D,,,,,2017-03-03 05:58:31,2018-03-14 12:57:11,9653.0,AUS - Join Day to Accept,N/A,L,S,0.0
49,24144882,ded5f6086e735459e8aaf0cecddd8798ff8fe920e9432...,I,D,live.com.au,Hotmail,O,D,,,,,2017-03-03 05:58:31,2018-03-14 12:57:11,9653.0,AUS - Join Day to Accept,N/A,C,S,0.0